### ISSUE TITLE
Compilation question

### ISSUE THREAD

**Issue by Doreinie** [rosasurfer/mt4-mql#11]
Hi, I found your EA and wanted to try it. did all download but find that the Metatrader editor cannot compile. Maybe there is a manual or installation guide available that I could not find yet?
I´m definitly a biginnner with this tool. Kindly allow my questions.
The sizes.mqh is creating probelms during compilation. Compile "complaints" are about the "." for all definitions.
#define FXT_HEADER.size 
Simiplar complaints in stddefines.mqh with e.g. 
#define Math.E     (again the "." make the trouble)

all in all I get 3005 errors and 712 warnings. for sure stupid me!

any help will be appreciated.
thanks

**Comment by rosasurfer** [comment]
Thank you for your interest. There are two options for you to proceed:
- The project requires a compiler <= build 509 to compile. You will find instructions in `https://github.com/rosasurfer/mt4-mql/tree/master/bin`
- Once a month (usually around the 1st) I provide a nightly release with precompiled binaries. You will find these at `https://github.com/rosasurfer/mt4-mql/releases`

The whole framework depends on a configuration and at the moment there is no proper documentation for it, except `https://github.com/rosasurfer/mt4-mql/blob/master/config/global-config.example.ini`. Please study and play with it and don't hesitate to ask.
