### ISSUE TITLE
Can i use python to create EA for MT4?

### ISSUE THREAD

**Issue by EmmanuelTom** [rosasurfer/mt4-mql#12]
I want to create mt5 bot because mt5 is intergrated with python but the problem is that my broker doesn't have option to copy trade from mt5! So please is they any how i can create EA for mt4 using python?

**Comment by ahangarha** [comment]
I don't think this question be related to this project. take a look at ZeroMQ and https://github.com/AustenConrad/mql4zmq

**Comment by EmmanuelTom** [comment]
> I don't think this question be related to this project. take a look at ZeroMQ and https://github.com/AustenConrad/mql4zmq

Hello Mr Ahangarha thank you,
I know is not related but really look for solution on this issue
