### ISSUE TITLE
SyncMainContext_init() DLL exception 

### ISSUE THREAD

**Issue by Julian-IronForge** [rosasurfer/mt4-mql#13]
Hello, using the latest release im trying to test out the snowroller EA. I get the following error when I try to run it in the tester:

ERROR:   EURUSD,M15  SnowRoller::init(2)->SyncMainContext_init()  [ERR_DLL_EXCEPTION]

I think it might be an access violation. The experts tab shows this:

2021.04.24 20:32:56.409	2018.01.02 00:00:08  SnowRoller EURUSD,M15: function 'SyncMainContext_init' call from dll 'rsfExpander.dll' critical error c0000005 at 6222B9F0.

I'm running mt4 build 1280.

Any ideas?

**Comment by rosasurfer** [comment]
Thank's for your interest. I'm assuming you experience this with release 0.106, right? Please start DebugView with admin rights and add the relevant output to this ticket. 

If you can compile by yourself please test the master branch and let me know the result (again with DebugView running in the background).
