### ISSUE TITLE
source code for dlls

### ISSUE THREAD

**Issue by magick93** [rosasurfer/mt4-mql#14]
Hello

This looks like a really excellent project! Nice work!

Is the source code for the dlls also open source?

Thanks and regards

**Comment by rosasurfer** [comment]
Please have a look at
https://github.com/rosasurfer/mt4-expander

Best,
Peter

magick93 wrote:

**Comment by magick93** [comment]
Wonderful!

Thank you Peter!

**Comment by rosasurfer** [comment]
btw: There is no need to compile the DLL by yourself. The version in the MQL4 repo is always up-to-date.
