### ISSUE TITLE
Can you provide ixxxOnArray functions for mt5, and correct the bugs in mt4

### ISSUE THREAD

**Issue by Janaue** [rosasurfer/mt4-mql#17]
In mql4, there are iRSIOnArray, iStdDevOnArray, iMAOnArray, iMomentumOnArray, iEnvelopesOnArray, iCCIOnArray, iBandsOnArray
and of course Metaquotes removed them in mql5.
Can you code them for mql5 and mql4 ?

Apparently there is a bug in iRSIOnArray
https://www.mql5.com/en/forum/327461
and he did his own version here
https://www.mql5.com/en/code/27478

where are those iRSIOnArray etc stored in mt4 folders?

**Comment by rosasurfer** [comment]
MetaQuotes removed above functions from MetaTrader5, in MetaTrader4  they are still available. Intentionally there is no support for MT5 from my side and there will never be, as I consider it fraudulent software.

I did not specifically test iRSIOnArray() for the mentioned bug but I know there is a similar bug with iStdDevOnArray(). At the moment I don't have plans to provide DLL implementations for those functions. If you have the need you can easily implement MQL versions of the logic by yourself (you provided a link to such a solution).
