### ISSUE TITLE
error

### ISSUE THREAD

**Issue by matth0p** [rosasurfer/mt4-mql#18]
hi, thanks for your sharing.
I'm having this problem and can't fix it.
Maybe I have a different version.
how can i fix it?
I have read the file in bin ( README )
but I don't understand if and how to fix it
Thanks again

![image](https://github.com/rosasurfer/mt4-mql/assets/140824831/6931ac0c-fb06-4112-9ba4-d9358e4178ba)

**Comment by syarief02** [comment]
which file is that brother? it says semicolon expected on the description. there must be somewhere missed the semicolon.

**Comment by rosasurfer** [comment]
This project is written in pure MQL4 (legacy MQL4), not in MQL5 as supported by current versions of MetaEditor.

For compilation you may use the MQL compiler [rosasurfer/mt4-mql/bin/metalang.exe](https://github.com/rosasurfer/mt4-mql/tree/master/bin/metalang.exe). You may replace that compiler with the most current MQL4 only compiler from build 509 (download link on the home page: [build 509](http://www.rosasurfer.com/.mt4/509%20last%20MQL4%20only/))
